services:
  base: &base
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        BUNDLE_WITHOUT: 'development:test'
        EXECJS_RUNTIME: 'Node'
        RAILS_ENV: 'production'
        RAILS_SERVE_STATIC_FILES: 'true'
    platform: linux/amd64
    tty: true
    stdin_open: true
    image: 914795699421.dkr.ecr.us-west-2.amazonaws.com/chatwoot:0.0.41

  rails:
    <<: *base
    ports:
      - '127.0.0.1:3000:3000'
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: always
    image: 914795699421.dkr.ecr.us-west-2.amazonaws.com/chatwoot:0.0.41

  sidekiq:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: always
    image: 914795699421.dkr.ecr.us-west-2.amazonaws.com/chatwoot:0.0.41
